In [13]:
from numpy import genfromtxt
import numpy as np
from collections import Counter

## Loading the actual and predicted labels for all models

In [14]:
actual = genfromtxt('actual.csv', delimiter=',')
logistic = genfromtxt('logistic.csv', delimiter=',')
cnn = genfromtxt('cnn.csv', delimiter=',')
dnn = genfromtxt('dnn.csv', delimiter=',')
svm = genfromtxt('svm.csv', delimiter=',')
rf = genfromtxt('rf.csv', delimiter=',')

actual_usps = genfromtxt('actual_usps.csv', delimiter=',')
logistic_usps = genfromtxt('logistic_usps.csv', delimiter=',')
cnn_usps = genfromtxt('cnn_usps.csv', delimiter=',')
dnn_usps = genfromtxt('dnn_usps.csv', delimiter=',')
svm_usps = genfromtxt('svm_usps.csv', delimiter=',')
rf_usps = genfromtxt('rf_usps.csv', delimiter=',')

## Combining the predictions of all models

In [21]:

combined_predicted = []
for i in range(len(logistic)):
    row = [int(logistic[i]),int(cnn[i]),int(dnn[i]),int(svm[i]),int(rf[i])]
    most_common,num_most_common = Counter(row).most_common(1)[0]
    combined_predicted.append(most_common)


combined_predicted_usps = []
for i in range(len(logistic_usps)):
    row = [int(logistic_usps[i]),int(cnn_usps[i]),int(dnn_usps[i]),int(svm_usps[i]),int(rf_usps[i])]
    most_common,num_most_common = Counter(row).most_common(1)[0]
    combined_predicted_usps.append(most_common)

## Comparing the combined predictions and actual values to calculate accuracy

In [25]:
from sklearn import metrics

def calculate_accuracy(x,y):
    count = 0
    for i in range(len(y)):
        if x[i] == y[i]:
            count+=1
    accuracy = count/float(len(y))
    return accuracy

accuracy = calculate_accuracy(combined_predicted,actual)
print("Combined accuracy using majority voting: ",accuracy)
print("Confusion matrix:\n%s" % metrics.confusion_matrix(actual, combined_predicted))

accuracy_usps = calculate_accuracy(combined_predicted_usps,actual_usps)
print("Combined accuracy for USPS using majority voting: ",accuracy_usps)
print("Confusion matrix:\n%s" % metrics.confusion_matrix(actual_usps, combined_predicted_usps))

Combined accuracy using majority voting:  0.9753
Confusion matrix:
[[ 978    0    5    1    0    1    1    0    2    0]
 [   0 1128    0    1    0    2    2    2    3    0]
 [   6    0  995    5    0    1    3    1    6    1]
 [   1    1    7  994    0    6    2    2    3    0]
 [   1    1    3    0  964    0    3    1    2   11]
 [   4    0    2   10    0  857    6    1    5    3]
 [   7    2    2    1    2    1  941    0    3    0]
 [   3    4    8    2    3    1    0 1009    3   11]
 [   3    0    5    6    4    4    4    3  928    3]
 [   5    5    1   10   11    2    0    4    6  959]]
Combined accuracy for USPS using majority voting:  0.44107205360268015
Confusion matrix:
[[ 639    2  342   43  285  158   65   51   50  365]
 [ 121  512  201  161  284  109   25  507   65   15]
 [ 118   11 1501   73   37  111   54   56   31    7]
 [  57    1  141 1395   12  296    4   48   38    8]
 [  20   80   48   25 1205  157   18  192  177   78]
 [  99   14  188  110   21 1445   53   36   26  